sudo: false
language: scala

scala:
  - 2.10.7
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

env:
  matrix:
    - PROJECT_SCOPE="" # root -> all projects
    - PROJECT_SCOPE="core-aggregate/"
    - PROJECT_SCOPE="macros-aggregate/"
    - PROJECT_SCOPE="argonaut-aggregate/"
    - PROJECT_SCOPE="test-aggregate/"
    - PROJECT_SCOPE="circe-aggregate/"
    - PROJECT_SCOPE="quill-aggregate/"
    - PROJECT_SCOPE="circe-aggregate/"
    - PROJECT_SCOPE="scalacheck-aggregate/"
    - PROJECT_SCOPE="upickle-aggregate/"
    - PROJECT_SCOPE="enumeratum-json4s/"
    - PROJECT_SCOPE="enumeratum-play/"
    - PROJECT_SCOPE="enumeratum-play-json/"
    - PROJECT_SCOPE="enumeratum-reactivemongo-bson/"


# Only run aggregation 2.12
matrix:
  # let's see if this acts as an override...
  include:
    - scala: 2.10.7
      script:
        - "travis_wait sbt ++$TRAVIS_SCALA_VERSION ${PROJECT_SCOPE}test:compile ${PROJECT_SCOPE}test:doc"
        - "travis_wait sbt ++$TRAVIS_SCALA_VERSION ${PROJECT_SCOPE}test"
    - scala: 2.12.4
      env:
        - PROJECT_SCOPE=""
      script:
        - travis_wait sbt ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - travis_wait sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
        - travis_wait sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
      after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls

script:
  - "travis_wait sbt ++$TRAVIS_SCALA_VERSION scalafmt::test ${PROJECT_SCOPE}test:compile ${PROJECT_SCOPE}test:doc"
  - "travis_wait sbt ++$TRAVIS_SCALA_VERSION ${PROJECT_SCOPE}test"


cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete